### ISSUE TITLE
Set up ContainerSSH

### ISSUE THREAD

**Issue by paseaf** [paseaf/containerSSH-honeypot#16]
## Goal
Should cover the following steps from the doc
- Step 7: Creating the ContainerSSH configuration file[¶](https://containerssh.io/guides/honeypot/#step-7-creating-the-containerssh-configuration-file)
- Step 7: Starting ContainerSSH[¶](https://containerssh.io/guides/honeypot/#step-7-starting-containerssh)

We should able to access ContainerSSH service from the gateway VM,

## Notes
- Do the containerSSh configuration in Terraform instead of Packer to make the image more general.
(the image is used for both gateway VM and logger vm)

## Possible subtasks
Follow the [ContainerSSH - Honeypot](https://containerssh.io/guides/honeypot/#step-4-creating-certificates-for-authentication-on-the-sacrificial-host) guide to set up ContainerSSH on the sacrificial VM.
- set up ContainerSSH
- firewall rules
- configurations

**Comment by bafread** [comment]
Open:
Step 4: Creating CA (@paseaf i got some problem here, if you have time and wanna try, feel free to.)

Done:
Step 3: Firewalling the sacrificial host (Friewall rule for Sacrificial VM is done, look at updated Terraform)
Step 6: Building the guest image on Sacrificial system (look at Packer and uupdated Readme)

**Comment by paseaf** [comment]
> Open: Step 4: Creating CA (@paseaf i got some problem here, if you have time and wanna try, feel free to.)
> 
> Done: Step 3: Firewalling the sacrificial host (Friewall rule for Sacrificial VM is done, look at updated Terraform) Step 6: Building the guest image on Sacrificial system (look at Packer and uupdated Readme)

I have the time but I also want to have a fair share of the group work. So I will keep myself from working on it for now, unless it's too late. :)
Btw, you could also create a draft PR and comment your steps there. It might be easier to refer to.

**Comment by bafread** [comment]
oh, no worry. thanks :)
btw never mind it's working now, i guess i did some typo on typing the host name.
![image](https://user-images.githubusercontent.com/106653277/172044859-ff1ba8e2-17a3-4ccf-9e5a-753c26006957.png)
