### ISSUE TITLE
Secure Prometheus

### ISSUE THREAD

**Issue by bafread** [paseaf/ContainerSSH-honeypot#39]
{logger-vm}:9091 now provides Prometheus access.
But maybe it's ok since they can't change anything?
Do some research

**Comment by bafread** [comment]
So.... there is an issue with securing Prometheus with docker.
It's too much work and not really worth it, that's why i'll just use a simple workaround with firewall.So since we got all metrices from Prometheus in Grafana, and in Grafana we can basically do what we can do in Prometheus, i'll just remove the Port release on firewall for prometheus. With these Prometheus will be unreachable from outside, but we can still working with prometheus's collected metrices in grafana. :)

**Comment by paseaf** [comment]
Disallow incoming ports for now
